spring:
  application:
    name: Project B
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
server:
  port: 8172
# 전역 개인 설정
bserver:
  # 리소스 외부 접근 URI
  resource-uri: /static/resources/
  # 계정 이름 변경 딜레이
  name-change-delay: 30
  # 인증 설정
  verification:
    password:
      # 비밀번호 변경 인증 키 만료 시간 (분 단위)
      expiration: 5
    email:
      # 이메일 인증 키 만료 시간 (분 단위)
      expiration: 1440
  # JWT 설정
  jwt:
    # 만료 시간 (모두 분 단위)
    expiration:
      # ID 검증 토큰 만료 시간
      sign: 5
      # 비밀번호 찾기 토큰 만료 시간
      password: 5
      # 접근 토큰 만료 시간
      access: 1440
      # 리프레시 토큰 만료 시간
      refresh: 2880