spring:
  config:
    activate:
      on-profile: dev
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 531364616543-ush91i5jl358h3gj3vv69943bgdg0hlg.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile,email
#            redirect-uri: http://localhost:3000/sign/oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/byeoruk_space?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1594
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      show_sql: true
      # 쿼리 포멧
      hibernate.format_sql: true
      # 쿼리 콘솔에 색깔로 표시
      hibernate.highlight_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: byeoruk.space@gmail.com
    password: zxdqrxkxneobkkqa
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
# 개인 설정
bserver:
  # 앱 URL
  app-url: http://localhost:5000
  # 개인 설정 - 리소스(파일)
  resource:
    # 서버 리소스 저장 경로
    path: 'C:/bserver-resources/'
    # 사용자 관련 리소스 설정
    member:
      # 사용자 아바타
      avatar:
        size: 100
        extensions: 'jpeg,jpg,png,gif'
      # 사용자 배너
      banner:
        size: 100
        extensions: 'jpeg,jpg,png'
  # 개인 설정 - JWT 설정
  jwt:
    # 시크릿 키
    secret: 1DiQ4pqOIAMRjmsZKX83hGwLG6yKT11e3mv7gAUKPNN3I2s7mr3P0SLGEJiGTxDjwaWpI1peek9bsgGT9iA2IFdSkfYZvUzw7TtxkkfvNAS9o10ldu7pwQ0oCASGH5UL
    # Issuer
    issuer: http://localhost:5000
# 로그
logging:
  # 쿼리 보여주기
  org.hibernate.SQL: DEBUG
  # 쿼리에 바인딩된 값 보기 (? 에 어떤 데이터 들어가는지 볼 수 있음)
  org.hibernate.orm.jdbc.bind: TRACE
  # Not work???
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  # 시큐리티 로그
  org.springframework.security: DEBUG