spring:
  application:
    name: Project B
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
server:
  port: 8172
# 전역 개인 설정
bserver:
  # 인증 설정
  verification:
    password:
      # 비밀번호 변경 인증 키 만료 시간 (분 단위)
      expiration: 5
  # JWT 설정
  jwt:
    # 만료 시간 (모두 분 단위)
    expiration:
      # ID 검증 토큰 만료 시간
      sign: 1
      # 비밀번호 찾기 토큰 만료 시간
      password: 1
      # 접근 토큰 만료 시간
      access: 1440
      # 리프레시 토큰 만료 시간
      refresh: 2880